### PR TITLE
Add github actions lint and test

### PR DESCRIPTION
**Pull request by dabonnie**

### CODE REVIEW

**Comment by dabonnie** [comment]
@thomas-moulard it's unclear to me why the build is failing with the current CMakeLists.txt.

**Comment by zmichaels11** [comment]
@dabonnie 
```
Cannot find source file:

src/moving_average_statistics/moving_average.cpp
```

**Comment by thomas-moulard** [comment]
I merged master, that should fix this issue.

**Comment by thomas-moulard** [comment]
@dabonnie Merging that in as it's better than nothing, seems like getting coverage for C++ needs some more work.

**Pull request merged**
