### PR TITLE
Install system metrics collector lib and executable

### PR DESCRIPTION
**Pull request by ahcorde**
Install system metrics collector lib and executable

### CODE REVIEW

**Comment by dabonnie** [comment]
Hey @ahcorde.

Thanks for the PR! However, since we're currently in active development we'd prefer to have our headers private until we finalize our API. We can review this in next week's ROS2 Tooling Working Group and, if you're curious, you can see our team roadmap here: https://app.zenhub.com/workspaces/aws-robotics-open-source-roadmap-5d9662bf4e1ec400011c53c6/board?repos=212657172

**Comment by thomas-moulard** [comment]
I think the part which is confusing is that the package is providing a lib, it should not, it should be a single binary, and this binary should be installed IMHO.

**Comment by zmichaels11** [comment]
@ahcorde 
Can you close this PR since this is work we do not plan to include yet?
I opened an issue #35 for this work, which we're gating after completion of https://github.com/ros-security/aws-roadmap/issues/3

**Comment by ahcorde** [comment]
Hi everyone!

Done, I pushed only the installation.

I was trying to use you library in an external executable. I will be watching you repository for futures updates. Let me know if can help with something

**Comment by thomas-moulard** [comment]
Merged, thanks a lot for the quick turn around on this PR!

**Pull request merged**
