### PR TITLE
Add clang build to GitHub action

### PR DESCRIPTION
**Pull request by thomas-moulard**

### CODE REVIEW

**Comment by thomas-moulard** [comment]
Blocked by https://github.com/ros-tooling/setup-ros2/pull/31

**Comment by thomas-moulard** [comment]
https://github.com/ros-tooling/setup-ros2/pull/32

**Comment by emersonknapp** [comment]
@thomas-moulard is this something you're still working on?

**Comment by thomas-moulard** [comment]
@emersonknapp not now, I'd like to get it merged eventually, but it will take time. We can either close, or keep open (as it's a draft?) - as you prefer.

**Comment by emersonknapp** [comment]
Closing for now, can reopen if work continues

**Pull request closed without merging**
